# Generated by Django 5.0.7 on 2024-07-17 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('organisation_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('booking_id', models.CharField(max_length=100)),
                ('date_of_booking', models.DateTimeField(max_length=100)),
                ('date_for_booking', models.DateTimeField(max_length=100)),
                ('amount', models.IntegerField(max_length=100)),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('complaint_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=100)),
                ('complaint', models.CharField(max_length=100)),
                ('complaint_date', models.DateTimeField(max_length=100)),
                ('contact', models.IntegerField(max_length=100)),
                ('complaint_status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('date_of_birth', models.DateTimeField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('fullname', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('salary', models.IntegerField(max_length=100)),
                ('date_of_birth', models.DateTimeField(max_length=100)),
                ('contact', models.IntegerField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='gamezonedetails',
            fields=[
                ('registration_number', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('place_name', models.CharField(max_length=100)),
                ('details', models.CharField(max_length=100)),
                ('contact', models.IntegerField(max_length=100)),
                ('services', models.CharField(max_length=100)),
                ('charges', models.IntegerField(max_length=100)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
